# Generated by Django 3.0.6 on 2020-05-13 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('image', models.FileField(blank=True, null=True, upload_to='media', verbose_name='Image')),
                ('body', models.TextField(verbose_name='Body')),
                ('author', models.CharField(max_length=40, verbose_name='Author')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Date Modified')),
                ('created', models.DateTimeField(verbose_name='Date Created')),
                ('publish', models.BooleanField(default=True, verbose_name='Publish')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug/Link')),
                ('send_mail', models.BooleanField(default=False, verbose_name='Send Mail')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.Category', verbose_name='Forum')),
            ],
        ),
    ]
