# Generated by Django 3.0.6 on 2020-06-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='banner',
            field=models.TextField(blank=True, null=True, verbose_name='Banner Code'),
        ),
    ]
