# Generated by Django 3.0.6 on 2020-06-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_auto_20200630_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='banner',
        ),
    ]
